  name: Playwright Tests

  on:
    push:
      branches:
        - main

  permissions:
    contents: read
    pages: write
    id-token: write

  jobs:

    test:
      runs-on: self-hosted

      steps:

        - name: Checkout Project
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 24

        - name: Install Playwright Browsers
          run: mvn exec:java "-Dexec.mainClass=com.microsoft.playwright.CLI" "-Dexec.args=install chromium"

        - name: Run Tests
          run: mvn clean test

        - name: Generate Allure Report
          if: always()
          run: mvn allure:report

        - name: Upload Allure Report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: allure-report
            path: target/site/allure-maven-plugin/

    deploy:
      needs: test

      runs-on: ubuntu-latest

      steps:

        - name: Download Allure Report
          uses: actions/download-artifact@v4
          with:
            name: allure-report
            path: allure-report

        - name: Upload GitHub Pages Artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: allure-report

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
